### ISSUE TITLE
create repo for heroku app to collect students notebook grades

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/ds-prep-course-2021#11]
create repo for https://github.com/LDSSA/ds-prep-course-2021/issues/10

**Comment by InesPessoa** [comment]
@buedaswag I also tried to create a repository, but I guess that I don't have permission for that. I can not conclude the process.

**Comment by buedaswag** [comment]
thanks Inês!
here it is:
https://github.com/LDSSA/nb-grades-collector

**Comment by buedaswag** [comment]
development phases:
* heroku app that receives a curl request with email, slack id, grade
    * stores  email, slack id, most recent grade, top grade
* get the grade from the students notebook so that we can send it
* (optional) implement student authentication

how to get slack id: https://moshfeu.medium.com/how-to-find-my-member-id-in-slack-workspace-d4bba942e38c

**Comment by buedaswag** [comment]
in this repo we have how we grade students's notebooks:
https://github.com/LDSSA/ldsagrader/tree/master/ldsagrader
