### ISSUE TITLE
create slackbot for student success 

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/ds-prep-course-2021#12]
create slackbot that sends messages to students that are behind on the exercises

**Comment by Juliana-R** [comment]
@buedaswag this idea is actually awesome. Can we do this for the Batch too? 😁

**Comment by buedaswag** [comment]
this is done

@Juliana-R of course we can! lets add that to the student success backlog?

**Comment by Juliana-R** [comment]
sure @rjna
