### ISSUE TITLE
QA of Prep Course (question)

### ISSUE THREAD

**Issue by Juliana-R** [LDSSA/ds-prep-course-2021#17]
@InesPessoa What is going to change from last year to this one and how will be QA organized in terms of deadlines and people QAing?

**Comment by InesPessoa** [comment]
Hi @Juliana-R . Last year we had reviewers and a QA team. The instructors were also reviewers, so besides the SLUs there were assigned, they also had SLUs were we were responsible for the reviewing process.  After that, the QA team, for each SLU, did a final review and deployed the material each Monday. 
This year, we will not separate the processes in reviewers and QA team. Instead, we will have the QA team, doing both processes, following the same procedures as in the DS academy.

**Comment by InesPessoa** [comment]
But unlike in the DS Academy, there is not a need of changing last year's exercises. The goal is to add more exercises or improve the ones that we already have, if the instructor feels that it is needed.

**Comment by Juliana-R** [comment]
Got it, thank you! 👍
