### ISSUE TITLE
Update DS Prep Course Wiki page - to do list

### ISSUE THREAD

**Issue by Juliana-R** [LDSSA/ds-prep-course-2021#19]
We need to update some info on the DS Prep Course Wiki page, namely:
- [x] Curriculum Spreadsheet link
- [x] Time requirements (are they still the same?);
- [x] The schedule of the SLUs.

@minhhoang1023 can you provide me the info to do this update?

**Comment by Juliana-R** [comment]
Meanwhile I'll update the schedule with the [info](https://docs.google.com/spreadsheets/d/1XdLEBoRJ6EOVjUrSdS_yJfoVRo2q60rYkPMYjtTeMvc/edit#gid=2041157571) I found.

**Comment by minhhoang1023** [comment]
All are updated!

**Comment by ramaroesilva** [comment]
Based on @minhhoang1023 last comment, should this issue be closed now?
