### ISSUE TITLE
password typing gives no visual feedback

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/ds-prep-course-2021#29]
we need a PR on the students repo that adds an item in the troubleshooting section that explains students that when you ask for sudo, or when asked to type a password, you dont get any visual feedback when you type it.

then whenever there's a command that asks for a password, we add a little note that directs to this troubleshooting point

here are some examples of situations where students had trouble with this:
* https://ldsaprepcourse2021.slack.com/archives/C01SLAS564Q/p1617025307148400
* https://ldsaprepcourse2021.slack.com/archives/C01SLAS564Q/p1617029300158900

**Comment by cimendes** [comment]
Adressed in #30

**Comment by buedaswag** [comment]
closed by https://github.com/LDSSA/ds-prep-course-2021/pull/30
