### ISSUE TITLE
Add guidance for those who have 2fa on Github

### ISSUE THREAD

**Issue by cimendes** [LDSSA/ds-prep-course-2021#33]
A student ran into an issue where it could not authenticate:

https://ldsaprepcourse2021.slack.com/archives/C01SLAS564Q/p1617114803308200

It looks like he had two factor authentication enabled. 

The Solution:
If you use 2FA, generate your token
When you get asked for the password, instead of the password, paste your token

should this info be added to the README?

**Comment by Juliana-R** [comment]
@cimendes please check this https://github.com/LDSSA/ds-prep-course-2021/issues/2 by @mariana-s-fernandes . A short aid on this was aided on the instructors README (ds-prep-course-instructors-2021). Feel free to adapt and PR the change for this README (ds-prep-course-2021)-

**Comment by Juliana-R** [comment]
my bad ! I was thinking this had been changed in the instructors but it was actually changed here. Sorry @cimendes 🤦
