### ISSUE TITLE
Replacing "<username>" - should be more clear

### ISSUE THREAD

**Issue by mariana-s-fernandes** [LDSSA/ds-prep-course-2021#39]
It is not total clear for the students that text between "<>" is to be replaced without the brackets. Maybe we should reinforce this idea a bit in the README

**Comment by cimendes** [comment]
Lot of students have been doing this mistake. I agree that a note would be useful! 👍

**Comment by Juliana-R** [comment]
Will close as this was addressed in https://github.com/LDSSA/ds-prep-course-2021/pull/43. Reopen if necessary.
