### ISSUE TITLE
Setup grading infrastructure for prep course

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/ds-prep-course-2021#6]
* Simple heroku app that receives requests from the students’s notebooks with the notebook grade
* we should probably create a repo for the app code

**Comment by buedaswag** [comment]
@rjna @InesPessoa how's progress on this?
do you need any help?

**Comment by Juliana-R** [comment]
Shall we close this?

**Comment by Juliana-R** [comment]
I believe this was already done in another repo. Please reopen if necessary.
