### ISSUE TITLE
Typo in Week 03_SLU05 under Pull Requests section

### ISSUE THREAD

**Issue by TechNic11** [LDSSA/ds-prep-course-2021#61]
Soon I'll start spotting bugs. For now, see my first issue below (a little typo. lol)

![MyFirstIssue](https://user-images.githubusercontent.com/81484757/115964836-efa88280-a4eb-11eb-82e7-d86f65a394e3.JPG)

**Comment by cimendes** [comment]
Ty for opening an issue! This one is fixed so I'm closing
