### ISSUE TITLE
Join Slack Workspace Group 

### ISSUE THREAD

**Issue by tommypx** [LDSSA/ds-prep-course-2021#82]
Hello, 

I have started the prep-course later. I would like to submit the weekly exercises, but for doing so, I need the Slack Id. As far as I have understood, I need to be added by yourvelves to the workspace. 

Thanks,

**Comment by minhhoang1023** [comment]
Hey @tommypx ! I's Minh - good to see that you're following that course. If you have passed all the asserts, you should get the right answer and there's no need to submit. The submission is only for us to keep track of students' progress.

**Comment by tommypx** [comment]
Hello Minh Hoang! Understood. Thank you for the clarification :)
