### ISSUE TITLE
Test the setup end-to-end and make sure it works

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/ds-prep-course-2021#9]

**Comment by Juliana-R** [comment]
who's the assignee(s) @buedaswag

**Comment by Juliana-R** [comment]
Please notice that there are **2 different setups** that should be tested!
- `ds-prep-course-2021/README.md`
- `ds-prep-course-instructors-2021/README.md`

**Comment by minhsf** [comment]
Can we prioritize ds-prep-course-instructors-2021/README.md? As instructors are starting to work on the materials

**Comment by Juliana-R** [comment]
I think so, but please don't forget that the students setup needs testing before next monday (when they start Week 0). 🙏

**Comment by Juliana-R** [comment]
Who is this issue assigned to?

**Comment by minhsf** [comment]
I don't know about this one, @buedaswag what's your thought on this?

**Comment by Juliana-R** [comment]
Shall we close this one? @buedaswag
